### PR TITLE
DEVDOCS-4719: [migrate] Shipping APIs, move example

### PR DESCRIPTION
**Pull request by bc-andreadao**
# [DEVDOCS-4719]

- Moved example for Shipping APIs. 

- Changed an example whose use case was needed, but whose properties were incorrect/outdated  

[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bc-andreadao** [comment]
@slsriehl All but 5 examples render on api-tester. 

Could use your help for these 5 examples:
- Create a Shipping Method: [request example](https://github.com/bigcommerce/api-specs/pull/1197/files#diff-18bbec893b1663e1527e872ed85c399cb86ec55460ae116e359bb589dc870beeR819) 
- Update a Shipping Method: [request example](https://github.com/bigcommerce/api-specs/pull/1197/files#diff-18bbec893b1663e1527e872ed85c399cb86ec55460ae116e359bb589dc870beeR1112)
- Update Carrier Connection: [request example](https://github.com/bigcommerce/api-specs/pull/1197/files#diff-18bbec893b1663e1527e872ed85c399cb86ec55460ae116e359bb589dc870beeR1204) 
- Create Carrier Connection: [request example](https://github.com/bigcommerce/api-specs/pull/1197/files#diff-18bbec893b1663e1527e872ed85c399cb86ec55460ae116e359bb589dc870beeR1238)
- Delete Carrier Connection: [request example](https://github.com/bigcommerce/api-specs/pull/1197/files#diff-18bbec893b1663e1527e872ed85c399cb86ec55460ae116e359bb589dc870beeR1294)

**Comment by slsriehl** [comment]
A few things:

- Please review the changes together.
- I merged in #1192. Please check render for line break issues.
- I converted more multiline examples to make it easier to reason about what's happening here.
- Does [this commit fix the example renders](https://github.com/bigcommerce/api-specs/pull/1197/commits/164e4e38f30584b34d0dffd636d2d6e8fb55dcfb)?

**Comment by slsriehl** [comment]
I re-replaced the br tags. I found something else that might be making the render worse when i did that, so I put the UPS packaging types in their own small table.

@bc-andreadao I'm gonna merge this and we'll see. if the examples don't render in the build, let's talk and/or you can open another PR.

**Review by slsriehl — APPROVED** [review]

**Comment by bc-andreadao** [comment]
All examples in this PR & the linting for the tables render on the site👍

**Pull request merged**
