### PR TITLE
DEVDOCS-4530: [edit] Abandoned Carts, move deprecated schema

### PR DESCRIPTION
**Pull request by bc-traciporter**
# [DEVDOCS-4530]

## What changed?
Moved the deprecated schema down so you see the current schema first

## Anything else?
Related PRs, salient notes, etc

[DEVDOCS-4530]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by markcmurphy** [comment]
Can you update target branch to staging?

**Comment by bc-traciporter** [comment]
@markcmurphy I changed the base branch to staging.

**Comment by bc-traciporter** [comment]
@markcmurphy I changed the base branch to staging.

**Review by stanzikratelbc — APPROVED** [review]
LGTM

**Pull request merged**
