### PR TITLE
DEVDOCS-5493: [update] add cleanup policy

### PR DESCRIPTION
**Pull request by bc-traciporter**
# [DEVDOCS-5493]
{Ticket number or summary of work}

## What changed?
Added the new webhooks cleanup policy

## Anything else?
Add related PRs, salient notes, ticket numbers, etc.

ping {names}

[DEVDOCS-5493]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bc-tgomez — APPROVED** [review]
Nice!

**Review by bc-andreadao — COMMENTED** [review]
The change looks fine. There are a few other places where we could change the description (unless there's a reason why you left them out):
- [Line 615](https://github.com/bigcommerce/api-specs/blob/27b5daa86f91adc0884308c2a9219d8d9f9d7911/reference/webhooks.v3.yml#L615)
- [Line 464](https://github.com/bigcommerce/api-specs/blob/27b5daa86f91adc0884308c2a9219d8d9f9d7911/reference/webhooks.v3.yml#L464)
- [Line 228](https://github.com/bigcommerce/api-specs/blob/27b5daa86f91adc0884308c2a9219d8d9f9d7911/reference/webhooks.v3.yml#L228)

**Comment by bc-traciporter** [comment]
Thanks @bc-andreadao, @zvuki  said he wanted just the POST and PUT webhook endpoints updated (Create and Update a webhook). So I am not sure if I should update these or not. @zvuki thoughts?

**Review by bc-stephen-hilliard — COMMENTED** [review]
Looks good

**Review by zvuki — APPROVED** [review]

**Comment by zvuki** [comment]
I'd update everywhere where `is_active` is mentioned, so it's crystal clear :)

**Review by bc-andreadao — APPROVED** [review]

**Pull request merged**
