### PR TITLE
DEVDOCS-3557 fix(shipping): SHIPPING-700 Update Customs Info API docs 

### PR DESCRIPTION
**Pull request by bc-andreadao**
[DEVDOCS-3557](https://jira.bigcommerce.com/browse/DEVDOCS-3557)

Changes for shipping api docs were merged to DEVDOCS-3557 in [PR 626](https://github.com/bigcommerce/api-specs/pull/626). These changes now need to merged to master branch.

### CODE REVIEW

**Review by traci707 — APPROVED** [review]
LGTM!  
Do you also need to change shipping v2 OAuth scopes as well?

**Comment by bc-andreadao** [comment]
@traci707 For your question above, I got a confirmation from @agchan12 that V2 scope currently does not need to be changed

**Comment by traci707** [comment]
@bc-andreadao Thanks Andrea

**Review by slsriehl — APPROVED** [review]
very nice

**Pull request merged**
