### PR TITLE
DEVDOCS-4378: [update] Get a Cart, update response body schema

### PR DESCRIPTION
**Pull request by markcmurphy**
- [DEVDOCS-4378]

## What changed?
* fix `line_items`
* restructure refs

[DEVDOCS-4378]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bc-andreadao** [comment]
For carts V3, I tested `line_items` and `line_item` for the carts V3 endpoints. I made a commit to fix the incorrect schema (incorrect schema in screenshot 1). It now looks like screenshot 2. If you would prefer I suggest rather than commit, I can do that next time

incorrect schema

correct schema

**Comment by bc-andreadao** [comment]
Create a Cart
Get a Cart
Update Customer ID
Add Cart Line Items
Update Cart Line Item
Delete Cart Line Item

**Review by bc-traciporter — APPROVED** [review]
LGTM

**Review by slsriehl — APPROVED** [review]
so fresh and so clean clean

**Pull request merged**
