### PR TITLE
DEVDOCS-4491: [net new] Checkouts, Create checkout token

### PR DESCRIPTION
**Pull request by bc-traciporter**
# [DEVDOCS-4491]

## What changed?
changed `checkout-id` to `checkoutId`

## Anything else?
Related PRs, salient notes, etc

[DEVDOCS-4491]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by slsriehl — CHANGES_REQUESTED** [review]
@bc-traciporter How does this fail? Let's document the error codes.

**Review by stanzikratelbc — DISMISSED** [review]
Made some minor changes, checks are still failing, @bc-traciporter and @slsriehl we need to address failures before we can merge @bc-traciporter and @slsriehl

**Review by stanzikratelbc — DISMISSED** [review]
All the errors have been fixed now, so this is good to merge.

**Review by slsriehl — APPROVED** [review]
good work all.

**Pull request merged**
