### PR TITLE
Devdocs 4431 fix endpoint and clean up file

### PR DESCRIPTION
**Pull request by bc-traciporter**
# [DEVDOCS-4431]

## What changed?
changed endpoint from `/v3/settings/marketing/abandoned-cart-emails` to `/v3/marketing/abandoned-cart-emails`

## Anything else?
Cleaned up errors in file

[DEVDOCS-4431]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by stanzikratelbc — APPROVED** [review]
Looks good to me.

**Review by bc-tgomez — CHANGES_REQUESTED** [review]
Adjust all the `abandoned cart email` language to reflect the same and it should be good to go. 👍

**Comment by bc-traciporter** [comment]
@bc-tgomez I think you are right. I checked the other pages and the name of the endpoint is capitalized. I think it is considered to be a proper noun. So I changed Abandoned Cart Email to uppercase.

**Review by bc-tgomez — APPROVED** [review]
LGTM! 🥳

**Review by stanzikratelbc — APPROVED** [review]
LGTM

**Pull request merged**
