### PR TITLE
DEVDOCS-4681: [refine] Tax Rates + Zones, cleanup

### PR DESCRIPTION
**Pull request by bc-andreadao**
# [DEVDOCS-4681]

(Optional) query parameters for GET Tax Rates: `id:in` and `tax_zone_id:in`  

(`tax_zone_id:in` was incorrectly documented as "required")

[DEVDOCS-4681]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by theromulans — APPROVED** [review]
Thanks Andrea, appreciate these detail updates.

**Review by bc-traciporter — APPROVED** [review]
LGTM!

**Comment by bc-andreadao** [comment]
Space48 partners brought up an improved way of documenting our `id:in` query parameters [here](https://github.com/bigcommerce/api-specs/pull/785) to help with their automated parsing. The query parameter is now described as a comma-separated string, but defined as an array (of integers) in an unexploded form. Github file reference: [oas3.1 spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameter-object)

Just wanted to point out for @theromulans in case you had any comments on the technical side

**Review by theromulans — COMMENTED** [review]
Awesome, loving the new approach!

**Review by theromulans — APPROVED** [review]

**Review by slsriehl — APPROVED** [review]
😺

**Pull request merged**
