### PR TITLE
DEVDOCS-4793: [update] Upsert Price List records

### PR DESCRIPTION
**Pull request by bc-traciporter**
Removed response body for Upsert Price List records

### CODE REVIEW

**Comment by bc-andreadao** [comment]
@bc-traciporter I just tested the endpoint (see screenshot). The reporter meant to say this;
```
{
    "data": {},
    "meta": {}
} 
```
put operation

**Review by bc-andreadao — COMMENTED** [review]
The fix was better, though could be more accurate

**Comment by bc-traciporter** [comment]
@bc-andreadao I think you are confusing this PR with feedback for the same API. This change removes the  response body for Upsert Price List records.

**Comment by bc-andreadao** [comment]
@bc-traciporter Just to clarify, it would be more accurate if you changed the response body to:

```
{
    "data": {},
    "meta": {}
} 
```
I tested the endpoint, and that's what I got.

**Comment by bc-traciporter** [comment]
@bc-andreadao thank you for testing. I should have done that. thanks for your help. I will make the change.

**Review by bc-andreadao — APPROVED** [review]

**Pull request merged**
