### PR TITLE
DEVDOCS-5646, [update] Checkouts V3, Add line item discount limits to Add discount to checkout endpoint

### PR DESCRIPTION
**Pull request by bc-tgomez**
# [DEVDOCS-5646]

## What changed?
* Add discount limitations to the Add Discount to Checkout endpoint's description

## Anything else?
Add related PRs, salient notes, ticket numbers, etc.

ping @valentindellangela @bc-traciporter 

[DEVDOCS-5646]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bc-traciporter — DISMISSED** [review]
Left a suggestion but feel free to leave it as it is.

**Comment by valentindellangela** [comment]
I think this message is already or should be added to this open PR instead https://github.com/bigcommerce/api-specs/pull/1517 - it hasn't been merged because the project isn't done yet and we don't want to publish the documentation before it's being made available.

**Comment by valentindellangela** [comment]
> @valentindellangela are you saying we need to wait until you give us the go ahead to merge this PR.

This bit
> You'll get an error message if you try adding a manual line item discount on a cart with a promotion or coupon applied. The same limitations apply if you try adding a coupon or promotion to a cart with an existing manual line item discount.

Sounds related to our WIP project yes.

**Comment by bc-traciporter** [comment]
@valentindellangela ok, no problem, we will wait to merge.

**Comment by bc-tgomez** [comment]
Closing branch as it has now been moved into the new [Docs SSOT Repo](https://github.com/bigcommerce/docs/tree/DEVDOCS-5646-Orders-Promotions-Target-Line-Items-to-Distribute-Discount-via-API).

**Pull request closed without merging**
