### PR TITLE
DEVDOCS-4182: Orders v3 YAML file is malformed

### PR DESCRIPTION
**Pull request by S48-Mo**
# [DEVDOCS-](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-)

## What changed?
* There was a malformed line in `orders.v3.yml` that was added during some previous merge operation. This PR rectifies it.

### CODE REVIEW

**Review by traci707 — COMMENTED** [review]
I am wondering why this text is needed because it says All failure response, there are no individual responses.

**Comment by S48-Mo** [comment]
Hi @traci707 thanks for coming back to us. That is how the 503 response code for that batch create refund endpoint was written prior. The description could be deleted entirely or re-worded to something more appropriate. How about `Internal Server Error`?

**Comment by traci707** [comment]
@markcmurphy It's your call on how you want to re-word it.

**Comment by slsriehl** [comment]
DEVDOCS-4182

**Review by markcmurphy — APPROVED** [review]

**Pull request merged**
