### PR TITLE
docs(checkout): CHECKOUT-7093 Introduce tax_included field of cart field for V3 checkout endpoint

### PR DESCRIPTION
**Pull request by bc-mackxu**
# [CHECKOUT-7093](https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7093)

## What changed?
* Introduce tax_included field of cart field for V3 checkout endpoint

Ping @bigcommerce/checkout @bigcommerce/dev-docs

### CODE REVIEW

**Comment by slsriehl** [comment]
@bc-keith do we have a CSS epic for this one?

**Comment by slsriehl** [comment]
[DEVDOCS-4628], [CSS-920]

**Comment by slsriehl** [comment]
@bc-mackxu merging this to the DEVDOCS ticket branch. cc @bc-traciporter

**Comment by bc-mackxu** [comment]
Thank you @slsriehl

**Pull request merged**
